name: AndroidBuild

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Optional: helps debug if APK path is wrong
      - name: List build outputs
        run: ls -R app/build/outputs

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: handheldexp-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
